import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#82d3de",
        "primary-container": "#006d77",
        "surface-container-low": "#f4f2ff",
        "surface-dim": "#d7d8f4",
        "outline": "#6f797a",
        "on-primary-fixed": "#001f23",
        "surface": "#fbf8ff",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e0fc",
        "primary": "#00535b",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#00201e",
        "tertiary-fixed": "#acefe7",
        "surface-container-high": "#e6e6ff",
        "inverse-on-surface": "#f1efff",
        "on-surface": "#181a2e",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#90d3cb",
        "on-secondary-container": "#663b00",
        "surface-tint": "#006972",
        "surface-container": "#edecff",
        "on-secondary-fixed": "#2c1700",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#286d67",
        "on-tertiary-fixed-variant": "#00504b",
        "secondary": "#895100",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffdcbc",
        "background": "#fbf8ff",
        "secondary-container": "#fd9d1a",
        "on-primary-container": "#9becf7",
        "tertiary": "#01544f",
        "on-error": "#ffffff",
        "on-background": "#181a2e",
        "on-surface-variant": "#3e494a",
        "on-primary-fixed-variant": "#004f56",
        "on-tertiary-container": "#a9ece4",
        "surface-bright": "#fbf8ff",
        "secondary-fixed-dim": "#ffb86b",
        "outline-variant": "#bec8ca",
        "primary-fixed": "#9ff0fb",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#82d3de",
        "inverse-surface": "#2d2f44",
        "surface-container-highest": "#e0e0fc",
        "on-secondary-fixed-variant": "#683d00"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "unit": "8px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "stack-lg": "32px",
        "container-max": "1200px",
        "stack-sm": "8px",
        "margin-mobile": "16px"
      }
    },
  },
  plugins: [],
};
export default config;
